c-cube/ocaml-containers

- opam
Uselful to do "opam pin add ." in the source directory.
> Added name and dev fields in the OPAM file for local pinning.

- AUTHORS.md
- _oasis
- doc/intro.txt
- src/data/CCPersistentArray.ml
- src/data/CCPersistentArray.mli
This implements persistent arrays in a way that is similar to the implementation of the persistent hash tables already present.
> Persistent array

- src/core/CCPrint.ml
- src/core/CCPrint.mli
It seems strange to not have a function to print characters individually, so there it is.
> New CCPrint.char function

- src/data/CCIntMap.ml
- src/data/CCIntMap.mli
- src/data/CCTrie.ml
- src/data/CCTrie.mli
- src/data/CCWBTree.ml
- src/data/CCWBTree.mli
This PR provides map and mapi functions for CCIntMap, CCTrie and CCWBTree.
> Provide map and mapi for some of the map types

- src/core/CCList.ml
- src/core/CCList.mli
> add CCList.range_by

- AUTHORS.adoc
- src/core/CCList.ml
- src/core/CCList.mli
> Add a tail-recursive implementation of List.combine

- AUTHORS.adoc
- src/core/CCList.ml
- src/core/CCList.mli
Fixes #135. 
~~This is a **work in progress** pull request. Once this is complete I will remove [WIP] label from pull request.~~ It should be ready for review/merge then.
TODO
Implement stack exception safe
- ~~[ ] `CCList.combine`~~ Already done
- ~~[ ] Add qtests for `CCList.combine`~~ Already done.
> Implement safe version of List.split and List.combine

- AUTHORS.adoc
- src/core/CCVector.ml
This adds test for the empty vector case, and fixes `CCVector.append_array` in said case.
In celebration of containers' 1000th test, I also added myself to the authors list.
> Tests for CCVector.append{,_array} and fix for CCVector.append_array

- src/core/CCString.cppo.ml
- src/core/CCString.mli
> Add String.is_empty

- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
- src/core/CCArray_slice.mli
- src/core/CCChar.mli
- src/core/CCInt64.mli
- src/core/CCList.ml
- src/core/CCList.mli
- src/core/CCListLabels.mli
- src/core/CCMap.mli
- src/core/CCRandom.mli
- src/core/CCSet.mli
- src/core/CCString.mli
- src/iter/CCKList.mli
- src/iter/CCKTree.ml
- src/iter/CCKTree.mli
- src/iter/CCLazy_list.mli
- src/sexp/CCSexp.mli
- src/unix/CCUnix.mli
Ajout de commentaires (provenant de OCaml 4.06.1). 
Corrections quelques typos.
> Adding comments

- src/core/CCList.ml
- src/core/CCList.mli
- src/core/CCListLabels.mli
Small function CCList.tail_opt.
(with test & CCList.mli / CCListLabels.mli)
> Adding CCList.tail_opt

- src/core/CCList.ml
Test _CCList.tail_opt_ now correct.
> Correcting test CCList.tail_opt

- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
- src/core/CCArray_slice.mli
- src/core/CCBool.mli
- src/core/CCEqual.mli
- src/core/CCFloat.mli
- src/core/CCFormat.mli
- src/core/CCFun.mli
- src/core/CCHash.mli
- src/core/CCHashtbl.ml
- src/core/CCHashtbl.mli
- src/core/CCHeap.ml
- src/core/CCHeap.mli
- src/core/CCIO.mli
- src/core/CCInt.mli
- src/core/CCInt64.mli
- src/core/CCList.mli
- src/core/CCListLabels.mli
- src/core/CCMap.ml
- src/core/CCMap.mli
- src/core/CCOpt.mli
- src/core/CCOrd.mli
- src/core/CCPair.mli
- src/core/CCParse.mli
- src/core/CCRandom.mli
- src/core/CCRef.mli
- src/core/CCResult.mli
- src/core/CCSet.mli
- src/core/CCString.mli
- src/core/CCVector.mli
La Saga Commentaires continue ...
> Adding more comments

- AUTHORS.adoc
- src/core/CCFun.ml
- src/core/CCFun.mli
Hi!
This adds a new `CCFun.iterate` function that computes the nth-iterate of a function. That is, that function composed with itself n times.
Let me know what you think.
Thanks!
> Add CCFun.iterate

- AUTHORS.adoc
- src/core/CCFloat.ml
- src/core/CCFloat.mli
am I using ``@since NEXT_RELEASE`` correctly ?
> Add infix operators to CCFloat

- src/core/CCInt32.ml
- src/core/CCInt32.mli
- src/core/containers.ml
Seems to be a junior job.
Hoping not to make too many junior mistakes !
> Adding CCInt32 module

- src/core/CCNativeint.ml
- src/core/CCNativeint.mli
- src/core/containers.ml
> Adding CCNativeint

- src/data/CCBijection.ml
- src/data/CCBijection.mli
Discussion:
http://lists.ocaml.org/pipermail/containers-users/2018-February/000042.html
> Add Bijection. https://en.wikipedia.org/wiki/Bijection

- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
- src/core/CCArray_slice.mli
- src/core/CCFormat.mli
- src/core/CCHeap.mli
- src/core/CCInt.mli
- src/core/CCInt64.mli
- src/core/CCList.mli
- src/core/CCListLabels.mli
- src/core/CCOpt.mli
- src/core/CCParse.mli
- src/core/CCRef.mli
- src/core/CCSet.mli
- src/core/CCString.mli
- src/core/CCUtf8_string.mli
- src/data/CCBijection.mli
- src/data/CCDeque.mli
- src/data/CCPersistentHashtbl.mli
- src/data/CCSimple_queue.mli
- Adding blank lines (to please odoc)
- Style modifs
- Typos
- Adding CCList.intersperse & CCList.interleave to CCListLabels.
> Few Comments corrections

- src/core/CCString.ml
- src/core/CCString.mli
I'm not sure about the name though. The function taken as argument is the opposite of what `CCString.filter` is waiting for but it made sense to me.
Any comments or suggestion on another name or if they should mimic `CCString.filter` ?
> Add CCString.{,r}drop_while

- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
- src/core/CCArray_slice.ml
- src/core/CCArray_slice.mli
. The goal is to start EACH (humpf...) comment line showing the usage of the function. That is:
```
(** [foo_name arg1 arg2 ...] followed by the description .... *)
```
. Additions/modifications comments (files CCArray / CCArrayLabels / CCArray_slice).
. Small typos.
> Improving comments presentation

- src/core/containersLabels.ml
- src/unlabel.ml
> add containersLabels.ml

- AUTHORS.adoc
- src/core/CCResult.ml
- src/core/CCResult.mli
Closes #238
There you go!
The test is a bit verbose and might be a little overkill. Let me know if you'd like me to try and make it more concise, I'm not super familiar with `qtest` yet!
> Add CCResult.iter_err

- src/core/CCResult.mli
I may add more doc in the future. Maybe, the best plan is to merge this just before the next release.
> [WIP] Work on documentation

- README.md
> ocamldebug section in the README

- src/unlabel.ml
fix https://github.com/c-cube/ocaml-containers/pull/227#issuecomment-469780960
> don't use Compenv.module_of_filename

- src/core/CCArray.ml
- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
This is my first ever PR containing OCaml code, so please double-check everything and tell me what needs to be corrected and/or done differently.
I've used [CCList.ml](https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCList.ml#L1704) and [CCList.mli](https://github.com/c-cube/ocaml-containers/blob/master/src/core/CCList.mli#L709) (links are to the relevant parts of the code) as a guidelines, but I'm not sure if this is the way to do it (e.g. everything was added manually).
Also, if there is a reason why this was not included in the first place, feel free to reject this PR.
> add CCArray.Infix

- src/data/CCDeque.ml
- src/data/CCDeque.mli
functions added:
CCDeque.remove_back
CCDeque.remove_front
CCDeque.update_back
CCDeque.update_front
> add CCDeque.{remove_*;update_*}

- src/core/CCArray.ml
- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
- src/core/CCChar.ml
- src/core/CCChar.mli
- src/core/CCHeap.ml
- src/core/CCHeap.mli
- src/core/CCList.ml
- src/core/CCList.mli
- src/core/CCListLabels.mli
- src/core/CCPair.ml
- src/core/CCPair.mli
- src/core/CCSet.ml
- src/core/CCSet.mli
- src/core/CCVector.ml
- src/core/CCVector.mli
> Adding to_string

- src/data/CCDeque.ml
Change the definition of the type in CCDeque to remove the Zero cell.
This new type enforce one invariant.
> change type of CCDeque

- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
- src/core/CCBool.mli
- src/core/CCChar.mli
- src/core/CCFloat.mli
- src/core/CCFormat.mli
- src/core/CCFun.mli
- src/core/CCHash.mli
It is a continuation of PR https://github.com/c-cube/ocaml-containers/pull/219 .
(Almost 2 years ago. Well,well...).
Question: 
The mixture of _Pervasives.foo_ and _Stdlib.foo_ is growing.
For a next PR I propose to replace _Pervasives_ by _Stdlib_.
Do you agree?
> Comments presentation modifications.

- src/sexp/CCSexp.ml
Hello,
In `CCSexp`, this PR escape empty atoms with quotes (`""`), otherwise `` `List [ `Atom "" ] `` would be formatted as `()`, which is `` `List [] ``.
It seems the tests were expecting that (`sexp_valid`), was this an intended behavior ?
> CCSexp: Escape empty atoms

- src/core/CCVector.ml
- src/core/CCVector.mli
Rename CCVector.remove to CCVector.remove_unordered and create a new CCVector.remove that keep the order of the element in the vector.
> CCVector.remove

- src/core/CCFloat.ml
- src/core/CCFloat.mli
A small first contribution adding something that I was missing that is present in Stdlib. Let me know if something could be improved.
> Add CCFloat.pi

- src/core/CCArray.ml
- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
Remove function define in the stdlib and in Infix
> chore(array): clean CCArray and CCArrayLabels

- src/core/CCInt.ml
- src/core/CCInt.mli
- src/core/CCInt32.ml
- src/core/CCInt32.mli
- src/core/CCInt64.ml
- src/core/CCInt64.mli
- src/core/CCNativeint.ml
- src/core/CCNativeint.mli
- src/core/dune
- src/core/mkshims.ml
Update CCInt{,32,64} and CCNativeint for 3.0
Fix #303
> CCInt{,32,64} and CCNativeint

- src/core/CCArray.mli
- src/core/CCArrayLabels.mli
- src/core/CCList.mli
- src/core/CCListLabels.mli
Continuation of https://github.com/c-cube/ocaml-containers/pull/310
> comments modifs

- src/core/CCFun.ml
- src/core/CCFun.mli
> CCFun: put infix operators in Infix module

- src/core/CCList.ml
- src/core/CCList.mli
- src/core/CCListLabels.mli
> CCList: add reduce function

- src/data/CCImmutArray.ml
> CCImmutArray: add tests

- src/core/CCString.mli
- src/core/CCStringLabels.mli
Syncing CCString.mli & CCStringLabels.mli comments.
> Syncing comments

- src/core/CCHash.mli
There's Warning 50 now. :sweat_smile:
> fix(hash): resolve ambiguous doc comment of bytes

- qtest/make.ml
- src/core/CCFormat.ml
- src/core/CCFormat.mli
> use `stag` for color handling in CCFormat 

- containers.opam
- qtest/dune
- src/bencode/containers_bencode.ml
- src/bencode/containers_bencode.mli
- src/bencode/dune
- src/core/CCHeap.ml
- src/core/CCIO.ml
- src/core/CCList.ml
- src/core/CCString.ml
- src/core/CCVector.ml
- src/data/CCDeque.ml
- src/data/CCFQueue.ml
- src/data/CCMixtbl.ml
- src/data/CCMixtbl.mli
- src/data/CCPersistentHashtbl.ml
- src/threads/CCPool.ml
- src/threads/CCTimer.ml
- src/top/dune
A small module to parse/print Bencode values. Bencode is really simple
and can embed binary strings easily, unlike JSON.
> add Containers_bencode

- src/core/CCSeq.mli
Thanks for making this library!
> Fix some typos

- src/core/CCParse.ml
- tests/core/t_parse.ml
- test: add test for CCParse
- fix(CCParse): fix issue in `recurse`
- fix bug in CCParse
- another fix for CCParse and slices
- remove dbg message
> fix ccparse slice

- src/core/CCList.ml
- src/core/CCList.mli
- src/core/CCListLabels.mli
- tests/core/t_list.ml
Closes #444 
Let me know if the test is sufficient 😄
> CCList: add unfold

- src/core/CCVector.ml
- src/core/CCVector.mli
- tests/core/t_vector.ml
Just adding a version of `fold` with indices for `CCVector`.
> CCVector: Add function foldi
