c-cube/ocaml-containers

src/core/CCArray.ml
src/core/CCArray.mli
src/core/CCList.ml
src/core/CCList.mli

I was looking for existing tests on these modules but couldn't find any. The tests I wanted to add were something like this:
```OCaml
(* Should return 2 *)
CCList.fold_while (fun acc b -> if b then acc+1, `Continue else acc, `Stop) 0 [true;true;false;true]
(* Should return 2 *)
CCArray.fold_while (fun acc b -> if b then acc+1, `Continue else acc, `Stop) 0 (Array.of_list [true;true;false;true])                                                                                                                      
```

fold_while implementation for CCList and CCArray (fixes #29)

---

README.md

The existing instructions did not work. I found that running `make tests` will tell you to do `ocaml setup.ml -configure --enable-tests` if you didn't before, but the instructions I changed it to works on master and seem more to the point than the warning given after running `make tests`.
In general I found it somewhat confusing on how I was supposed to enable the tests as there seems to be several ways to go about it.

Update README.md test instructions

---

AUTHORS.adoc
src/core/CCRandom.ml
src/core/CCRandom.mli

This pull request modifies the implementation of `CCRandom.split_list` to make the underlying distribution uniform. All tuples (x_1,..,x_n) satisfying the constraint ∑ x_k = i should now appear with the same probability.
To test this property, I have also added a statistical uniformity test. Like any statistical test, this test has a non-zero false positive rate; but these false positives should be quite rare with the confidence interval that I have chosen (every few years assuming one test by day). 
I have also added a `sample_without_rejection` function since it can be quite useful and was needed for the implementation of `split_list`. The current implementation use rejection sampling, which works well when the number of sample is small compared to the cardinal of the sampled set.

Uniform implementation for CCRandom.split_list

---

src/core/CCError.ml
src/core/CCError.mli

```join``` and ```both``` are convenience functions which exist in Jane Street's version of ```Result``` and ```Or_error```- I thought they would also be nice to have in ``CCError`.

join / both applicative functions for CCError

---

AUTHORS.adoc
src/data/CCPersistentHashtbl.ml
src/data/CCPersistentHashtbl.mli

This patch brings the merge function of CCPersistentHashtbl
in line with the merge functions of other maps
(Map, BatMap from batteries, CCWBTree). In particular, its signature
changes from the restrictive
```merge: (key -> 'a option -> 'a option -> 'a option) -> 'a t -> 'a t -> 'a t```
to a more general
```merge: (key -> 'a option -> 'b option -> 'c option) -> 'a t -> 'b t -> 'c t```

Make CCPersistentHashtbl.S.merge more general.

---

src/data/CCRingBuffer.mli

A one line change to Make so that the OCaml array type is exposed as a standard OCaml array. Without this, the internal array module's type is opaque and thus not composable with any libraries which uses arrays of the same element type (in my case, floats). 
Example:
```OCaml
let arr:float array = let module RB = CCRingBuffer.Make(CCFloat) in RB.to_array (RB.create 0)
````
yields
```OCaml
Error: This expression has type RB.Array.t
but an expression was expected of type float array 
```
With the fix, though:
```OCaml
val arr : float array = [||]
```
(opposed to the opaque type ```RB.Array.t``` as it is in master)
Edit: formatting

show ocaml array type concretely in Make sig

---

src/core/CCResult.mli

~default arg for `map_or`, as well as function, should not depend on the type of error case.

Fixes map_or

---

src/threads/CCLock.ml
src/threads/CCLock.mli

I've added `CCLock.try_with_lock` as I've found it useful when attempting to access one of many locked resources without blocking. There is no other way that I've found to query the lockedness of a mutex and, if unlocked, acquire it atomically.
I've also updated the documentation for `get` as I initially thought it disregarded the mutex and enabled one to access the data directly. I had attempted to use this in conjunction with `CCLock.mutex` and `Mutex.try_lock` to work-around the lack of `CCLock.try_with_lock` however this caused a deadlock as the mutex had already been acquired when I called `get`.
I'm happy to work with you to get this functionality merged so let me know if there are changes you'd like to see.
Thanks!

threads/CCLock: add try_with_lock to wrap Mutex.try_lock

---

src/threads/CCSemaphore.ml

This is segfaulting (on ubuntu 16.04 and 16.10) when trying to release the unlocked mutex in the release stage (in general this is an undefined behavior AFAIK).

Fix with_acquire: release a non locked mutex is UB

---

AUTHORS.adoc
src/core/CCOpt.ml
src/core/CCOpt.mli

This adds the following functions to CCOpt:
* `map_lazy` -- for consistency with `get_lazy`
* `or_` -- as a named alternative to `<+>` and to allow `or_lazy`
* `or_lazy` -- for consistency with `get_lazy`
* `to_result` -- for consistency with other core type conversions
* `to_result_lazy` -- for consistency with `get_lazy`
* `of_result` -- for consistency with other core type conversions

Plugs some holes in CCOpt

---

AUTHORS.adoc
README.adoc
src/data/CCBV.ml
src/data/CCBV.mli

A couple of notes:
- I didn't fully understand why the original representation used only 62 bits. I changed it to use 63. Maybe there was some confusion about the hamming distance/count bits code? But I believe that it also works for negative values.
- I changed slightly the behavior or `of_list`, `length` and `resize`.
- In general, the more that I worked on this the more that I'm puzzled about the actual usefulness of bitvectors that resize. I understand that it would be convenient, but for most use cases, the user is tracking a known set of states. In these cases I would imagine it an error for things to somewhat silently change size. It also leads to weird cases where `let i = 10000000 in get t i`  will succeed but then `set t i` might allocate a big chunk of memory. There could would …

Size tracking bitvector

---

src/data/CCFQueue.ml

The test "take_back empty = None" never succeeded because take_back_exn raised InvalidArgument instead.

CCFQueue bugfix for take_back_exn

---

src/core/CCList.ml

See discussion [here](https://discuss.ocaml.org/t/a-new-list-map-that-is-both-stack-safe-and-fast/865/32) and more detailed benchmarking [here](https://github.com/janestreet/base/pull/25#issuecomment-333614561). This is the same as @paurkedal's code, and I'm relying on his benchmarking that found an optimal point at 9-tuples for X86-64 processors.
Running containers' benchmark, at 500,000 elements, I see an increase from n=62 to n=111 after this patch.

List: Use efficient chunking algorithm for tail-recursive list map

---

src/data/CCCache.ml
src/data/CCCache.mli

The purpose of this PR is to offer a way for user to manually add some values to a cache.
One pattern that I often have in my code currently is to compute some kind of function (usually translation between ASTs) with a cache, but also allow to a posteriori fix some values for this function. Usually, the way it happens is I define the translation function, and then further in the code, extensions give some kind of semantics to certain values, which in this case means forcing the translation on some values. In case it seems surprising, all this forcing happens during the program initialization, so that the meaning of the translation does not change during execution. However, I find it a nice way to have a reasonably extensible translation function.
In any case, my goal could be achieved by …

Add CCCache.add

---

src/data/CCTrie.ml

Following #157, this PR fixes a fatal use of the polymorphic equality function in ```CCTrie```.

Fix CCTrie.Make: Remove polymorphic comparison

---

src/core/CCList.ml
src/core/CCList.mli

Implement suggestion by @bluddy: https://github.com/c-cube/ocaml-containers/pull/161#issuecomment-348809182
Do we want to do the same thing for every index-based functions ? (```insert_at_idx```, ```set_at_idx```, …)

Allow negative indexes in CCList.remove_at_idx

---

AUTHORS.adoc
src/core/CCList.ml

Looks like the implementation of CCList.repeat reversed the list at the start and at the end - this adds a test and removes one of the reversals so the result comes out the right way round.

Don't reverse twice in CCList.repeat

---

AUTHORS.adoc
src/data/CCRAL.ml

`drop_tree` drops everything when drop-count is equal length-1:
``` ocaml
val l : int L.t = <abstr>
- : unit = ()
```
This PR seems to do the right thing.

CCRAL: Fixed bug in drop_tree_ / drop / take_drop

---

.travis.yml
appveyor.yml

Done using @yomimono's [autoci](https://github.com/yomimono/autoci).

Enable support for Travis CI and Appveyor

---

src/iter/CCLazy_list.ml
src/iter/CCLazy_list.mli

This little function is quite useful in practice
```ocaml
> to_list(default (return 1) (return 2));;
- : int list = [2]
> to_list(default (return 1) (empty));;
- : int list = [1]
```

Add <|> to CCLazy_list

---

src/core/CCOpt.ml
src/core/CCOpt.mli

Hi!
There was `CCOpt.flat_map`, but no `CCOpt.flatten`. Rather than redefining it in our codebase I'm sure it can find a home in containers :smiley: 
Thanks!

Add CCOpt.flatten

---

AUTHORS.adoc
src/core/CCEqual.mli
src/core/CCInt32.mli
src/core/CCInt64.mli

Operators are defined in the Infix module.
This module was included in the .ml file but not in the .mli file
I also made an (maybe) unrelated change to CCEqual. I can remove it

Fix Int32 and Int64 operators are not visible

---

src/core/CCHeap.ml
src/core/CCHeap.mli

Allow to pass module implementing `compare` without implementing `leq`
There is some discussion here: https://github.com/c-cube/ocaml-containers/pull/223#issuecomment-392784680
`TOTAL_ORD` is not the usual name.
I added a test but I did not succeed in running it

Add CCHeap.Make_from_compare

---

benchs/jbuild
benchs/run_benchs.ml

- Add Map as a reference, as this is the only efficient implementation in OCaml's standard library
- Add Clarity.Vector from the [clarity](https://github.com/IndiscriminateCoding/clarity) library
- New benchmarks for set at index and push
What's missing:
- CCFun_vec.set (no implementation)
- CCRAL.push and Clarity.Vector.push were missing and implemented inefficiently in terms of append
Maybe interesting for later:
- `iter` / `map`/ `filter`
- `append` (concatenating two `'a t`s)
- `push_front`

More benchmarks for immutable vectors

---

AUTHORS.adoc
src/core/CCInt.ml
src/core/CCInt.mli

This will allow writing something like `CCInt.(10 + 5 ** 2)` instead of `CCInt.(10 + (pow 5 2))`

Support using ** for exponentiation in CCInt

---

AUTHORS.adoc
src/core/CCResult.ml
src/core/CCResult.mli

Useful for raising meaningful exceptions when dealing with results with string errors.
Equivalent functions include https://github.com/dbuenzli/rresult/blob/master/src/rresult.mli#L138 & https://github.com/janestreet/base/blob/master/src/result.mli#L60

Add CCResult.get_or_failwith

---

src/data/CCRingBuffer.ml
src/data/CCRingBuffer.mli

A few notes:
- I added `dummy` to the signature of the Array in order to use it from `MakeFromArray`, which is a breaking change and not terribly nice. Open to better suggestions (add the `Elt` submodule to `Array`?)
- It doesn't seem to be possible to add comments to `$inject` blocks
- On my machine, `live_blocks` is 2 if deleting is properly implemented and `capacity b + 2` otherwise, so I believe the GC test is reasonably stable, but of course I'm also open to other approaches

Fix #235 for CCRingBuffer

---

AUTHORS.adoc
src/core/CCIO.ml

It looks like the eof reference was accidentally left behind after some old refactoring

Remove unused reference in CCIO.read_chunks

---

src/core/mkshims.ml

The Stdlib module has been introduced from OCaml 4.07 and not OCaml 4.08. As a consequence submodules from the standard library were not available anymore when you open the Containers module.

Fix Containers.Stdlib on OCaml 4.07

---

README.md
containers.opam
dune
dune-project

We recently released `mdx.1.5.0` which contains fixes for some of the bugs you ran into so I took the liberty to open a PR re-enabling the mdx check of the README.
I also rewrote the dune rules by hand as `mdx rule` still needs to be improved a little. As a matter of fact it's going to be replaced by a proper dune integration for mdx in an hopefully near future!
Let me know what you think!

Re-enable mdx tests

---

src/core/CCChar.ml
src/core/CCFloat.ml
src/core/CCIO.ml
src/core/CCIO.mli
src/core/CCInt.ml
src/core/CCString.ml

Two other occurences weren't fixed because their exceptions are not documented: https://github.com/c-cube/ocaml-containers/blob/4bc01a0b8251dae4e2e5ae7648b5c03911804c23/src/unix/CCUnix.ml#L313-L314
https://github.com/c-cube/ocaml-containers/blob/4bc01a0b8251dae4e2e5ae7648b5c03911804c23/src/core/CCIO.ml#L282

Avoid catch-all handlers

---

benchs/dune
benchs/objsize.ml
benchs/run_benchs.ml
benchs/run_objsize.ml

- Add test to print the object size of various containers in heap words
- Add [Sek.Persistent](http://cambium.inria.fr/~fpottier/sek/doc/sek/Sek/index.html)
- Add bench for iter to List
- Add bench for to_array, cons and fold (over a cons-ed structured) to Seq
The cons-ed variants of Iter/Gen/Seq are a bit silly since they are not usually used like that. I was just curious how well closures do, feel free to complain.
Adds dependencies to Base and Sek. I've commented out Core_kernel for now.
To do for later: Compare Sek.Ephemeral, CCVector, CCRingBuffer, Base.Queue, etc.
Object sizes:
```
0      1     10    100   1000  10000
Stdlib.List         :      0      3     30    300   3000  30000
Stdlib.Array        :      1      2     11    101   1001  10001
Stdlib.Hashtbl      :     22     26 …
```

More benchmarks

---

src/core/CCArray.ml
src/core/CCArray.mli
src/core/CCArrayLabels.mli
src/core/CCList.ml
src/core/CCList.mli
src/core/CCListLabels.mli

They both have `?eq:('a -> 'a -> bool) -> 'a -> 'a t -> bool` as signature with `eq = Stdlib.(=)` by default.

harmonize CCList.mem and CCArray.mem

---

src/core/CCVector.ml
src/core/CCVector.mli

Fix name confusion between `shrink` and `shrink_to_fit` by introducing `resize` instead of `shrink`.

feat(vector): transform shrink in resize

---

src/core/CCResult.ml
src/core/CCResult.mli

Resolves #317.
The one other minor change I've made is that instead of redundantly declaring infix signatures `<*>` and `>|=` once at the top-level and then once again in `Infix`, they are now imported into the top-level of the `CCResult` module signature via `include module type of Infix`.

CCResult: add <$> operator

---

src/core/CCPair.ml
src/core/CCPair.mli

map1 -> map_fst
map2 -> map_snd
map_fst -> fst_map
map_snd -> snd_map
introduce map2 and map_same2
Fix #316

break(CCPair): use more standard name for some map functions

---

src/core/CCList.ml
src/core/CCList.mli
src/core/CCListLabels.mli

See #333.
In principle, we could also add such functions for all monads with a zero (e.g. options). I only did it for lists however. 
Also, as there's no sensible zero for `CCResult` (the only module already featuring a `guard` function), we could keep calling the added function `guard` (as in Haskell) instead of `mguard`, if you see fit.

Add a guard function for list comprehensions

---

src/core/CCList.ml
src/core/CCList.mli
src/core/CCListLabels.mli

Implements #335.
Sorry, the former PR about `mguard` is also inside the PR and already pushed... Hope you can sort this out.
Also : I have only implemented the function for List for the time being. Indeed, it seems neither CCSeq nor OSeq come with a let syntax, and `zip` is already implemented in OSeq.

Add List.combine_chop and corresponding (and&) synchronized product

---

.gitignore
fuzz/ccsexp_parse_string_does_not_crash.ml
fuzz/ccutf8_string_uchar_to_bytes_is_same_as_simple_version.ml
fuzz/dune
fuzz/list.sh
fuzz/run.sh

Spawned from #338 
Adds the following fuzzing tests:
- `ccsexp_parse_string_does_not_crash`
- The fuzzing test that revealed #338 
- `ccutf8_string_uchar_to_bytes_is_same_as_simple_version`
- Tests `CCUtf8_string.uchar_to_bytes` against a simpler implementation of the equivalent

Init files for fuzzing

---

src/core/CCFormat.ml
src/core/CCFormat.mli

Resolves #314.  This PR adds the following to the `CCFormat` module:
- `space` (alias to `pp_print_space`), `cut` (alias to `pp_print_cut`), and `break` (wrapper around `pp_print_break` that turns it into an `(int * int) printer`).
- `append` (runs two `unit printer`s sequentially), `++` (alias to `append`), and `append_l` (runs a list of printers sequentially).

CCFormat: append combinator and space/break/cut aliases

---

src/core/CCMap.ml

This is comparable in conciseness and clarity as an explicit try/with
but it paves the way for a more efficient implementation using the
`update` from the Stdlib which, I presume, uses a one-pass algorithm.
I didn't do the same for `Hashtbl` because it isn't clear that there is a
beneficial such implementation for hash tables.

CCMap: implement {of,add}_*_with family of function with update

---

.gitignore
fuzz/clean.sh
fuzz/run.sh
fuzz/run_all.sh

This PR adds two small scripts I made for a fuzzing pipeline
- `clean.sh` just removes all fuzzing input/output files
- `run_all.sh` does parallel fuzzing of jobs in batches with (CPU core count - 1) afl instances with time out in stages
- For instance, if we have 4 CPU core count, and we have 5 fuzzing tests, then 3 tests are run in parallel until time out, then remaining 2 tests are run in parallel until time out
- I currently set the time out to 10m, but you can adjust that at `test_timeout="10m"` to something else
`run.sh` is also upgraded mostly for interacting with `run_all.sh`
Note: CPU core count - 1 instead of exactly CPU core count afl instances is desirable because afl uses 100% of CPU, and leaving no processing time to other processes makes it very difficult to continue …

Small upgrade to fuzzing suite scripts

---

src/core/CCInt.ml
src/core/mkshims.ml

- Remove popcount from shims
- Express large integer literals using bitshifts
Also ran `make test` in a 4.11.1+32bit switch since it doesn't seem to be covered by CI at the moment.

Fix integer overflow warning on jsoo (#346)

---

src/core/CCSeq.ml
src/core/CCSeq.mli

The functions are implemented the same way as in `oseq` and their documentation is inspired from their counterparts in `Stdlib.List`.
Closes #361.

CCSeq: Add `for_all` and `exists`

---

Makefile

In my environment the dune cache is enabled by default, and I observed that this lead to `make test` not actually running the tests. I don't know if this a good way to resolve this issue.

test: ensure tests are run by disabling dune cache

---

src/data/CCRAL.ml
src/data/CCRAL.mli

It seems like a waste to repeat the search for an index to both get
the element at that index and then to remove it. The added
`get_and_remove_exn` operation performs a `remove` but returns the
found element rather than forgetting it.

feat(CCRAL): add `get_and_remove_exn` operation

---

src/core/CCOpt.ml
src/core/CCOpt.mli

`CCOpt.get_exn` has a lot of potential to create a horrible UX, since it fails with "CCOpt.get_exn" error message, which explains nothing, and it also makes exception traces not very informative since the failure comes inside of a library function.
It's better to force the user to supply a helpful error message, if the user chooses to use a function that raises an exception for `None`.
A real-life example of `get_exn` making someone's live miserable can be found at https://github.com/daypack-dev/timere/pull/23

Add CCOpt.get_exn_or and deprecate CCOpt.get_exn

---

src/core/CCHash.ml
src/core/CCHash.mli

Same algorithm as `CCHash.string`.
Did not find test cases for `CCHash.string` so I did nothing for testing `CCHash.bytes`. Happy to add some test cases if needed.

Add CCHash.bytes

---

CHANGELOG.md
src/core/CCSeq.ml
src/core/CCSeq.mli

This PR suggests a change to `CCSeq.to_array`.
The change is motivated by the surprising behavior of `CCSeq.to_array` 
when the underlying seq depends on state. This surprising behavior can
be illustrated with this comparison between the behavior of `to_list` and
`to_array`:
```
let s = unfold (fun i -> if i < 3 then let x = !r in incr r; Some (x, succ i) else None) 0 in
to_array s
;;
- : int array = [|5; 6; 7|]
let s = unfold (fun i -> if i < 3 then let x = !r in incr r; Some (x, succ i) else None) 0 in
to_list s
;;
- : int list = [1; 2; 3]
```
The solution suggested here is to construct an intermediate list, to cash
the elements of the seq while we obtain the length of items, and thus 
prevent traversing the Seq twice. This requires the allocation of one 
intermediate list, but further …

Make CCSeq.to_array behave better with stateful sequences

---

src/core/CCResult.ml
src/core/CCResult.mli

A function I use a lot when applying CCResult over optionals - e.g. in a translation of ASTs a fragment like:
```
| AST_from.Return expr -> let+ expr = opt_map trans_expr expr in AST_to.Return expr
```
where `expr` is an optional expression of type `a option` and `trans_expr` maps from `a -> ('b,'err) result`

adding opt_map to simplify result function application over optionals

---

src/core/CCList.ml
src/core/CCList.mli
src/core/CCListLabels.mli

There's a bunch of simple assoc list helpers I use quite often and I think I'm not alone, so I'd like to add them to containers:
* `keys`: returns a list of all keys.
* `values`: returns a list of all values.
* `map_values`: applies a function to all values.
If you have objections against the naming of `map_values` or any implementation details, let me know. In particular, containers lean towards making a fold over an empty list a failure, while these functions return an empty list in that case—let me know if you think it should be handled differently.

New assoc list helpers: `keys`, `values`, and `map_values`

---

src/core/cpp/dune

We’ve suddenly started to see builds for [ocaml-multicore/multicorestests](https://github.com/ocaml-multicore/multicorestests) on bytecode-only OCaml when ocaml-containers became a recursive dependency because `cpp` is configured to build only on native.
See for instance this build:
https://github.com/shym/ocaml-containers/actions/runs/3674985755/jobs/6213853972#step:8:17
With this patch, the bytecode-only OCaml can build the project: https://github.com/shym/ocaml-containers/actions/runs/3675109065/jobs/6214130472
It might be interesting to go further and ensure that the test suite also can be run on bytecode?

Allow explicit fallback to bytecode for cpp

---

.github/workflows/compat.yml
.github/workflows/main.yml
tests/core/dune
tests/core/t_vector.ml
tests/data/dune
tests/thread/dune

As a followup to #421, this PR runs the test suite also on a bytecode-only switch, after fixing what must be fixed so that it works.

Allow tests to run on a bytecode-only platform

---

src/core/CCVector.ml

fix(CCVector): always obtain a copy of array before using unsafe_{set,get}

---

src/core/CCIO.mli

This PR clarifies the behavior of `walk` and `read_dir ~recurse:true` by documenting that:
- `walk p` always includes `p`
- `read_dir ~recurse:true` only includes file paths (whereas `read_dir ~recurse:false` can include directory paths)

[doc] CCIO.File.walk

---

README.md
src/data/CCMultiMap.ml
src/data/CCMultiMap.mli

The commit message documents all the changes made so I'll just paste it here:
> Rename functions find_left and find_right in the bidirectional multimap to find_left_iter and find_right_iter respectively to reflect their usage, and add new functions to replace the old find_left and find_right that return a list of values rather than an iterator, to make the signatures of CCMultiMap.S and CCMultiMap.BIDIR cohere. Additionally, change the return type of S.find_iter from `t -> key -> (value -> unit) -> unit` to `t -> key -> value iter`. These types are the same though, it's just for clarity since CCMultiMap already exposes an iter type
Note that this is a breaking change since it changes the signature of `CCMultiMap.BIDIR`. A cursory GitHub search did not reveal many usages of the …

Fix CCMultiMap

---

src/pp/containers_pp.ml
src/pp/containers_pp.mli
tests/core/t_pp.ml

nested pp extensions

---

src/core/CCBool.ml
src/core/CCBool.mli
tests/core/t_bool.ml

Just some cute boolean combinators.
Example usage:
```ocaml
[true;false;true;false;true] |> List.filter_map (Bool.if_then (Fun.const 1));;
- : int list = [1; 1; 1]
[true;false;true;false;true] |> List.map (Bool.if_then_else (Fun.const 1) (Fun.const 0));;
- : int list = [1; 0; 1; 0; 1]
let t () = print_endline "Yes" in
let f () = print_endline "No" in
let select = Bool.if_then_else t f in
select true;
select false;;
Yes
No
- : unit = ()
```
etc.

CCBool: Add functions if_then and if_then_else

---

Makefile
benchs/run_benchs.ml
run_bench_hash.sh
run_benchs.sh
src/core/CCList.ml

- chore: add scripts to run benchmarks
- update benchs to add 2 distinct flat_map to it
- perf: accelerate `List.append` and `List.flat_map` on 5.1

faster List.flat_map

---

src/core/CCVector.ml

These warnings are silenced by the use of -nolabels in the compilation flags (which I understand is designed to make the life of the CC*Labels file easier, not let minor labeling mistakes sleep in.)

CCVector: fix two labels-omitted warnings

---

benchs/dune
benchs/run_benchs.ml
src/pvec/containers_pvec.ml
src/pvec/containers_pvec.mli
src/pvec/dune
tests/core/t_fun.ml
tests/pvec/dune
tests/pvec/t.ml
tests/pvec/t_pvec.ml

persistent vectors based on clojure's, in a new containers.pvec sub-library

containers.pvec

---

src/monomorphic/CCMonomorphic.ml

perf: use a monomorphic impl for CCMonomorphic.{min,max}

---

src/core/CCVector.ml
src/core/CCVector.mli

Add a function to return the index as well as the item found.  I think this is useful with `CCVector.slice_iter`.

feat: add CCVector.findi

---

src/core/CCEither.mli

Changed "form OCaml 4.12" to "from OCaml 4.12".

Update CCEither.mli fixing typo in docstring

---

src/core/CCEither.mli
src/core/CCString.ml
src/core/CCString.mli
src/core/CCStringLabels.mli
tests/core/t_string.ml

If you're open to it, I implemented a couple of apparently-missing functions in the `CCString` module, added corresponding tests, and updated `CCString.mli` and `CCStringLabels.mli` accordingly.

Add `take_while` and `rtake_while` to `CCString`, addressing #463

---

src/core/CCChar.ml
src/core/CCChar.mli
tests/core/t_char.ml

I've added some functions to check whether a given character is uppercase, lowercase, a letter, a digit, or white-space, respectively. These are particularly useful in building predicates for `CCString` functions like `contains`, `exists`, &c. Let me know what you think, and if you want any changes.
The names align with the convention set by Stdlib's `Char` of indicating the character encoding nominally.

Additional functions for the `Char` module to check common character properties
